
services:
  nginx:
    image: nginx:alpine
    container_name: hungry-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx configuration file
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # SSL certificate and key (self-signed for now)
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ../../
      dockerfile: infra/docker/backend.Dockerfile
    container_name: hungry-backend
    ports:
    - "3001:3001"
    env_file:
     - ../../backend/.env
  

  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/frontend.Dockerfile
    container_name: hungry-frontend
    expose:
      - "80"
    depends_on:
      - backend
